---
version: "3.8"
services:
  movies:
    image: manikantacherry/moviespayy:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: manikantacherry/trainpayy:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: manikantacherry/rechargepayy:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: manikantacherry/dthpayy:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
